version: "3.8"

services:
  mysql:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: ADMIN
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: TESTS
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - app-network  
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
#    environment:
    ports:
      - "8000:8000"
    networks:
      - app-network  
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    depends_on:
      - mysql #might need to wait for mysql to be up and running 
volumes:
  node_modules: 
networks:
  app-network:
    driver: bridge